version: '3'

services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./db/:/root/db
    env_file:
      - ./.env
  backend:
    build: ../shop_backend/
    restart: always
    volumes:
      - static_value:/app/static
      - media_value:/app/media
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    build:
      context: ../shop-frontend/
      dockerfile: Dockerfile
    volumes:
      - static_value:/var/html/static
      - media_value:/var/html/media
    ports:
      - "80:80"



volumes:
  static_value:
  media_value: